apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpa-web-app-deployment
  labels:
    app: phpa-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpa-web-app
  template:
    metadata:
      labels:
        app: phpa-web-app
    spec:
      containers:
      - name: phpa-web-app
        image: alicescholze/web-app:v6
        ports:
        - containerPort: 3000
