apiVersion: v1
kind: Service
metadata:
  name: phpa-web-app-service
spec:
  selector:
    app: phpa-web-app
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  sessionAffinity: None
